README.md
src/index.js

I couldn't see a reason for this plugin to only work with nodejs runtimes, I've used it successfully with Python after a minor adjustment so that the warmup function runtime is overridden to nodejs6.1 rather than the providers default runtime.
Python early exit code I'm using is
```
if event.get('source', None) == 'serverless-plugin-warmup':
print('WarmUP - Lambda is warm!')
return 'Lambda is warm!'
```
Invoking the event
> START RequestId: ... Version: $LATEST
2017-05-06T10:55:40.488Z    ...    Warm Up Start
2017-05-06T10:55:40.751Z    ...    Warm Up Invoke Success: x-y-z { StatusCode: 200, Payload: '"Lambda is warm!"' }
2017-05-06T10:55:40.751Z    ...    Warm Up Finished with 0 invoke errors
END RequestId: ...
REPORT RequestId: ...  Duration: 329.97 ms Billed Duration: 400 ms     Memory …

Remove runtime dependency

---

README.md

Related to https://github.com/FidelLimited/serverless-plugin-warmup/issues/13
The issue was the way I was deploying the lambda in the VPC.
I've added a Gotcha section to the Readme so no one else has to spend half a day investigating this.

docs(readme): Add Gotchas section and info about deploying to VPC

---

src/index.js

If the stage / region values need to be resolved (file reference, etc.), they should be accessed after the package has been fully populated (not pre-populated, see Serverless Variables class).

Move stage and region resolution to after init

---

src/index.js

If the custom configuration needs to be resolved, e.g. by file reference, it is not available until the package has been populated (see Serveless Variables).

Move custom config resolution to after init

---

.travis.yaml

Let's at least enable Travis to enforce correct linting.
In the next commit, once the build works, I'll add the badge to the Readme.

Add Travis CI config

---

README.md
src/index.js

Adds optional `source` and `sourceRaw` field to customization. `source` will default to `{ "source": "serverless-plugin-warmup" }` if not configured.

allow customization of event source (fixes #26)

---

README.md
src/index.js

The default concurrency value is 1 and can be set in custom.warmup.concurrency for all lambdas and can be overridden by specifying a warmupConcurrency value at the function definition level.  I'm not super knowledgeable on YAML, node or developing serverless plugins so I wasn't sure if using <function>.warmup.concurrency would work since <function>.warmup is already being used as a specific config value (true/false/stage) rather than a config section.
Also, another value is passed along with the source to both the context and payload of the call, concurrencyIndex.  That's added in case someone wants special handling for the first X concurrent instances.
I've tested that this is working and is calling my lambda functions but using the AWS SDK to invoke the lambda instead of invoking …

Concurrency option for warming up X instances of of a lambda.

---

src/index.js

This should close #92 for good!
Haven't found a good lifecycle event to place the functions config initialization so that the names are already set and works for both package and deploy. Thus the duplication.

Fix missing function name

---

src/index.js

The default payload got stringified twice:
Line 169 and then Line 145

Fix payload being stringified twice

---

.travis.yml
package.json
src/index.js
test/constructor.test.js
test/hook.afterDeployDeploy.test.js
test/hook.afterPackageCreateDeploymentArtifacts.test.js
test/hook.afterPackageInitialize.test.js
test/utils/configUtils.js

This PR adds tests for pretty much everything except for the generated function which should be tested in every function inside `test/hook.afterPackageInitialize.test.js` using the approach of #111
Missing tests include:
* Global enabled
* Global disabled
* Global stage
* Global stages
* Global enabled - function disabled
* Global enabled - function stage
* Global enabled - function stages array
* Global disabled - function enabled
* Global disabled - function stage
* Global disabled - function stages array
* Global stage - function enabled
* Global stage - function disabled
* Global stage - function stages array
* Global stages array - function enabled
* Global stages array - function disabled
* Global stages array - function stage
* source
* source raw
* concurrency

Add more tests

---

README.md
src/index.js
test/hook.afterPackageInitialize.test.js

I find `source` a really misleading name since it actually indicates the payload which by default is `{ source: 'serverless-plugin-warmup' }`.
`payload` is a much more clear name.
As with other property changes, the plugin will stay backwards compatible.

Rename source to payload

---

src/index.js
test/hook.afterPackageInitialize.test.js

The goal of this PR is to allow the plugin setup using boolean as string like the scenario below:
```yml
warmup:
enabled: ${env:WARM_UP_ENABLED}
```
In the scenario above the value of `WARM_UP_ENABLED` is a string `"true"` and the plugin skips the creation of the warm function. With the PR the function will be created. 
The env var in question is set on a deployment shell script.

Handle enabled field with boolean value as string

---

.eslintrc.js
package-lock.json
package.json
src/index.js
test/hook.afterDeployDeploy.test.js
test/hook.afterPackageCreateDeploymentArtifacts.test.js
test/hook.afterPackageInitialize.test.js

eslint is more strict and configurable.
Also, it's been over a year that TC39 started the debate about why semicolons are important: https://github.com/tc39/ecma262/pull/1062

Replace standard with eslint

---

README.md
package-lock.json
src/index.js

We have a use case to dynamically change the warmup concurrency of our lambdas across different stacks at runtime rather than requiring a code change and deployment. I think this is really useful as sometimes we'd like to smooth out adhoc burst traffic we know will be coming without having to redeploy every stack.
This code change allows us to modify the concurrency of all lambdas, or just individual lambdas by just adding an environment variable.
The output looks like this:
```
2019-06-13T00:24:18.472Z	a92c57be-d4d7-40ed-b055-652fcc2bd45c	Warming up function: test-lambda with concurrency: 1
2019-06-13T00:24:18.550Z	a92c57be-d4d7-40ed-b055-652fcc2bd45c	Function environment variable warmup concurrency found: 5. Overwrote configured concurrency for test-lambda-2
2019-06-13T00:24:18.550Z …
```

Support dynamically overriding concurrency

---

README.md

According to https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_version.html only two values are accepted. This commit changes the invalid value to the most recent of the two acceptable version strings.

Update readme to use correct policy version

---

src/index.js

While playing with this wonderful plugin, I stumbled upon the following issue
```yml
service: debug
functions:
handler:
handler: index.handler
package:
artifact: app.zip
warmup:
concurrency: ${ssm:/patch/to/variable} # value "50"
```
Due to limitations from SSM Parameter Store, values are stored as `str`, while the handler in warmup assumes this is an `int`
```js
const functions = [
{
"name": "debug-dev",
"config": {
"enabled": true,
"payload": "{\"source\":\"serverless-plugin-warmup\"}",
"concurrency": "50"
}
}
];
```
This patch allows user to setup any valid expression `parseInt` accepts

Patch: concurrency from config force Number

---

src/index.js
test/utils/configUtils.js

AWS lambda have announced support for NodeJS 12 see https://aws.amazon.com/about-aws/whats-new/2019/11/aws-lambda-supports-node-js-12/

update nodejs runtime to 12.x

---

.travis.yml

Node.js13 was also added because there were settings other than LTS.
Close it if you don't need it.

Add Node.js 13 to CI setting

---

README.md

Not all events with "aws.events" as source should be treated as warmup events

Bug in Python code example

---

README.md
src/warmer.js
test/utils/configUtils.js

`nodejs14.x` is also now supported.
https://docs.aws.amazon.com/lambda/latest/dg/lambda-nodejs.html

feat: switch from `nodejs12.x` to `nodejs14.x`

---

src/schema.js

Adjust schema to the strict mode that is enabled by default since AJV v7.

Adjust schema to the strict mode

---

README.md
src/config.js
src/schema.js
src/warmer.js
test/hook.warmupAddWamersAddWamers.test.js

Optionally set a roleName for the warmers.
Sometimes the default generated Role name exceeds the IAM max name length of 64 characters.
This causes deployments to fail for some users if they do not disable the warmers for deployments. 
```
Error:
CREATE_FAILED: WarmUpPluginDefaultRole (AWS::IAM::Role)
1 validation error detected: Value 'apple-map-api-sandbox-ap-south-1-stack-sandbox-ap-south-1-default-role' at 'roleName' failed to satisfy constraint: Member must have length less than or equal to 64 (Service: AmazonIdentityManagement; Status Code: 400; Error Code: ValidationError; Request ID: 60b62c0f-18d8-4b63-80fe-672b1b5d8add; Proxy: null)
```
https://github.com/juanjoDiaz/serverless-plugin-warmup/blob/847b45cc675e8f12ea439b68283417feab562ef9/src/warmer.js#L25-L40
Optionally provide …

feat: optionally set warmer roleName if using default role

---

src/warmer.js
test/utils/configUtils.js
test/utils/generatedFunctionTester.js

Hi @juanjoDiaz,
My previous PR for upgrading to NodeJS 18 actually broke this library, because there's a major change on NodeJS 18 which is to update AWS SDK from v2 to v3, so I created this PR for upgrading AWS SDK to v3.
Please review and release my code or build your own version if you don't like my code :)
https://aws.amazon.com/blogs/compute/node-js-18-x-runtime-now-available-in-aws-lambda/
Thanks,
CJ

migrate to AWS SDK v3

---

src/config.js
test/hook.warmupAddWamersAddWamers.test.js

I ran into the following error in one of my projects:
```
TypeError: Cannot convert undefined or null to object
at Function.entries (<anonymous>)
at getConfigsByWarmer (project/node_modules/serverless-plugin-warmup/src/config.js:170:34)
at WarmUp.configPlugin (project/node_modules/serverless-plugin-warmup/src/index.js:89:10)
at PluginManager.runHooks (project/node_modules/serverless/lib/classes/plugin-manager.js:530:15)
at PluginManager.invoke (project/node_modules/serverless/lib/classes/plugin-manager.js:563:20)
at PluginManager.spawn (project/node_modules/serverless/lib/classes/plugin-manager.js:585:16)
at after:package:initialize (project/node_modules/serverless-plugin-warmup/src/index.js:64:71)
at PluginManager.runHooks (project/node_modules/serverless/lib/classes/plugin-manager.js:530 …
```

fix: handle missing warmup configuration

---

src/schema.js

Updating schema to support timezone, and method fields as per the changes made in serverless@3.39
https://github.com/serverless/serverless/blob/de62c71e30855eff688f032ff10b9ad22de13afc/lib/plugins/aws/package/compile/events/schedule.js#L81-L88

Update schema.js to support AWS::Scheduler::Schedule
