juanjoDiaz/serverless-plugin-warmup

README.md
package.json
src/index.js

Update sls and remove runtime validation

---

src/index.js

Fixes #9 
Set the function qualifier to SERVERLESS_ALIAS or $LATEST

Support serverless-aws-alias plugin.

---

README.md
src/index.js

This resolves #29 
I haven't been able to test much but the change seems tiny enough to be harmless and it doesn't introduce any breaking changes.

feat(options): update the warmer option to optionally take stages

---

README.md
src/index.js

Closes #46 
Full disclosure: I don't have any serverless project setup at the moment so I couldn't test it.

feat: Add role option for warmer

---

README.md

Improve iamRoleStatements documentation

---

README.md
src/index.js

This PR will add functionality of adding tags to warmup lambda function as request in #49 .

Adding tags for warmup lambda function

---

README.md
src/index.js

Supersedes #45 which seems like it was abandoned after my review.

Add default

---

src/index.js

Just a bit of cleaning up.
Avoid doing the same job (loading the config) twice and move all the checks to top-level hooks.

Minor improvements

---

README.md

Clarify permissions needed by WarmUp

---

src/index.js

Fix missing function name

---

package-lock.json
package.json
src/index.js

https://github.com/jprichardson/node-fs-extra/blob/master/docs/remove.md
https://github.com/jprichardson/node-fs-extra/blob/master/docs/outputFile.md

Remove bluebird: fs-extra already has promise support

---

.travis.yml
package-lock.json
package.json
test/index.test.js

+ Jest
+ Unit tests for getFunctionConfig
+ Pre-push hook to run tests
+ Update travis.yml to run tests

Add jest and unit tests for getFunctionConfig

---

src/index.js

Closes #123, #126 and supersedes #127

Improve codebase

---

README.md
package-lock.json
src/index.js
test/hook.afterPackageCreateDeploymentArtifacts.test.js

Support overriding `package`

---

README.md

Update example to node 8

---

src/index.js
test/hook.afterDeployDeploy.test.js
test/hook.afterPackageInitialize.test.js
test/utils/generatedFunctionTester.js

Fix alias qualifier on prewarm

---

src/index.js
test/utils/configUtils.js

Not add environment option to generate function if it's empty

---

README.md

Add Python example to readme

---

src/index.js

Loose type checks to allow references

---

README.md

Improve the documentation as requested in #150

Improve documentation about the configuration options

---

README.md
package-lock.json
package.json
src/index.js
test/hook.afterPackageInitialize.test.js

Configure context independently from payload

---

src/index.js
test/utils/configUtils.js

Add validation schema

---

README.md

Add python decorator example to readme

---

src/index.js
test/hook.afterDeployDeploy.test.js
test/utils/configUtils.js

Closes #220 
BREAKING CHANGE. Part of v5.

Remove latest alias

---

src/index.js
test/hook.afterPackageCreateDeploymentArtifacts.test.js
test/utils/configUtils.js

Closes #191 
BREAKING CHANGE. Part of v5.

Automatically exclude package level includes

---

.eslintrc.js
.npmignore
install_husky.js
package.json

Fixes #248 and supersedes #249

Fix issue with Husky and npm installs

---

src/index.js
test/hook.warmupPrewarmStart.test.js

fix: prewarm after function deploy

---

src/index.js

Fix prewarming CLI message typo

---

src/schema.js

[juanjoDiaz/serverless-plugin-warmup#345]

 Adds missing `alias` to schema additions
